spring:
  datasource:
    url: jdbc:mysql://localhost:3307/gonggus?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api

